type maskObjType = {
  [key in string]: maskType[];
};

export interface maskType {
  src: string;
  href: string;
  left: string;
  right: string;
}

const storeLink = {
  bts: 'https://smartstore.naver.com/rivermarket276/products/7229087032',
  viuum1: 'https://smartstore.naver.com/rivermarket276/products/7210389193',
  viuum2: 'https://smartstore.naver.com/rivermarket276/products/7222530807',
  garim: 'https://smartstore.naver.com/rivermarket276/products/7210265324',
  chramzone: 'https://smartstore.naver.com/rivermarket276/products/7229286968',
  goodmanner1:
    'https://smartstore.naver.com/rivermarket276/products/7245200256',
  goodmanner2:
    'https://smartstore.naver.com/rivermarket276/products/7245160562',
  hyosung: 'https://smartstore.naver.com/rivermarket276/products/7381458848',
  theGreen: 'https://smartstore.naver.com/rivermarket276/products/7380981745',
};

const maskList = {
  bts_black_01: {
    src: 'bts_black_01.png',
    left: 'bts_black_01_left.png',
    right: 'bts_black_01_right.png',
    href: storeLink.bts,
  },
  bts_cherry_01: {
    src: 'bts_cherry_01.png',
    left: 'bts_cherry_01_left.png',
    right: 'bts_cherry_01_right.png',
    href: storeLink.bts,
  },
  bts_green_01: {
    src: 'bts_green_01.png',
    left: 'bts_green_01_left.png',
    right: 'bts_green_01_right.png',
    href: storeLink.bts,
  },
  bts_mint_01: {
    src: 'bts_mint_01.png',
    left: 'bts_mint_01_left.png',
    right: 'bts_mint_01_right.png',
    href: storeLink.bts,
  },
  bts_orange_01: {
    src: 'bts_orange_01.png',
    left: 'bts_orange_01_left.png',
    right: 'bts_orange_01_right.png',
    href: storeLink.bts,
  },
  bts_pink_01: {
    src: 'bts_pink_01.png',
    left: 'bts_pink_01_left.png',
    right: 'bts_pink_01_right.png',
    href: storeLink.bts,
  },
  bts_purple_01: {
    src: 'bts_purple_01.png',
    left: 'bts_purple_01_left.png',
    right: 'bts_purple_01_right.png',
    href: storeLink.bts,
  },
  bts_skyblue_01: {
    src: 'bts_skyblue_01.png',
    left: 'bts_skyblue_01_left.png',
    right: 'bts_skyblue_01_right.png',
    href: storeLink.bts,
  },
  bts_white_01: {
    src: 'bts_white_01.png',
    left: 'bts_white_01_left.png',
    right: 'bts_white_01_right.png',
    href: storeLink.bts,
  },
  bts_yellow_01: {
    src: 'bts_yellow_01.png',
    left: 'bts_yellow_01_left.png',
    right: 'bts_yellow_01_right.png',
    href: storeLink.bts,
  },
  cz_beige_01: {
    src: 'cz_beige_01.png',
    left: 'cz_beige_01_left.png',
    right: 'cz_beige_01_right.png',
    href: storeLink.chramzone,
  },
  cz_black_01: {
    src: 'cz_black_01.png',
    left: 'cz_black_01_left.png',
    right: 'cz_black_01_right.png',
    href: storeLink.chramzone,
  },
  cz_grey_01: {
    src: 'cz_grey_01.png',
    left: 'cz_grey_01_left.png',
    right: 'cz_grey_01_right.png',
    href: storeLink.chramzone,
  },
  cz_navy_01: {
    src: 'cz_navy_01.png',
    left: 'cz_navy_01_left.png',
    right: 'cz_navy_01_right.png',
    href: storeLink.chramzone,
  },
  cz_white_01: {
    src: 'cz_white_01.png',
    left: 'cz_white_01_left.png',
    right: 'cz_white_01_right.png',
    href: storeLink.chramzone,
  },
  gm_beige_01: {
    src: 'gm_beige_01.png',
    left: 'gm_beige_01_left.png',
    right: 'gm_beige_01_right.png',
    href: storeLink.goodmanner1,
  },
  gm_black_01: {
    src: 'gm_black_01.png',
    left: 'gm_black_01_left.png',
    right: 'gm_black_01_right.png',
    href: storeLink.goodmanner1,
  },
  gm_grey_01: {
    src: 'gm_grey_01.png',
    left: 'gm_grey_01_left.png',
    right: 'gm_grey_01_right.png',
    href: storeLink.goodmanner1,
  },
  gm_pink_01: {
    src: 'gm_pink_01.png',
    left: 'gm_pink_01_left.png',
    right: 'gm_pink_01_right.png',
    href: storeLink.goodmanner1,
  },
  gm_white_01: {
    src: 'gm_white_01.png',
    left: 'gm_white_01_left.png',
    right: 'gm_white_01_right.png',
    href: storeLink.goodmanner1,
  },
  gr_beige_01: {
    src: 'gr_beige_01.png',
    left: 'gr_beige_01_left.png',
    right: 'gr_beige_01_right.png',
    href: storeLink.garim,
  },
  gr_berry_01: {
    src: 'gr_berry_01.png',
    left: 'gr_berry_01_left.png',
    right: 'gr_berry_01_right.png',
    href: storeLink.garim,
  },
  gr_celesteblue_01: {
    src: 'gr_celesteblue_01.png',
    left: 'gr_celesteblue_01_left.png',
    right: 'gr_celesteblue_01_right.png',
    href: storeLink.garim,
  },
  gr_coraltint_01: {
    src: 'gr_coraltint_01.png',
    left: 'gr_coraltint_01_left.png',
    right: 'gr_coraltint_01_right.png',
    href: storeLink.garim,
  },
  gr_oceanblue_01: {
    src: 'gr_oceanblue_01.png',
    left: 'gr_oceanblue_01_left.png',
    right: 'gr_oceanblue_01_right.png',
    href: storeLink.garim,
  },
  gr_peachcushion_01: {
    src: 'gr_peachcushion_01.png',
    left: 'gr_peachcushion_01_left.png',
    right: 'gr_peachcushion_01_right.png',
    href: storeLink.garim,
  },
  gr_rosewine_01: {
    src: 'gr_rosewine_01.png',
    left: 'gr_rosewine_01_left.png',
    right: 'gr_rosewine_01_right.png',
    href: storeLink.garim,
  },
  vm_ashgrey_01: {
    src: 'vm_ashgrey_01.png',
    left: 'vm_ashgrey_01_left.png',
    right: 'vm_ashgrey_01_right.png',
    href: storeLink.viuum2,
  },
  vm_gingerbrown_01: {
    src: 'vm_gingerbrown_01.png',
    left: 'vm_gingerbrown_01_left.png',
    right: 'vm_gingerbrown_01_right.png',
    href: storeLink.viuum2,
  },
  vm_lilacpurple_01: {
    src: 'vm_lilacpurple_01.png',
    left: 'vm_lilacpurple_01_left.png',
    right: 'vm_lilacpurple_01_right.png',
    href: storeLink.viuum2,
  },
  vm_sandbeige_01: {
    src: 'vm_sandbeige_01.png',
    left: 'vm_sandbeige_01_left.png',
    right: 'vm_sandbeige_01_right.png',
    href: storeLink.viuum2,
  },
  vm_black_01: {
    src: 'vm_black_01.png',
    left: 'vm_black_01_left.png',
    right: 'vm_black_01_right.png',
    href: storeLink.viuum1,
  },
  vm_grey_01: {
    src: 'vm_grey_01.png',
    left: 'vm_grey_01_left.png',
    right: 'vm_grey_01_right.png',
    href: storeLink.viuum1,
  },
  vm_ivory_01: {
    src: 'vm_ivory_01.png',
    left: 'vm_ivory_01_left.png',
    right: 'vm_ivory_01_right.png',
    href: storeLink.viuum1,
  },
  vm_lightsilver_01: {
    src: 'vm_lightsilver_01.png',
    left: 'vm_lightsilver_01_left.png',
    right: 'vm_lightsilver_01_right.png',
    href: storeLink.viuum1,
  },
  vm_pink_01: {
    src: 'vm_pink_01.png',
    left: 'vm_pink_01_left.png',
    right: 'vm_pink_01_right.png',
    href: storeLink.viuum1,
  },
  vm_white_01: {
    src: 'vm_white_01.png',
    left: 'vm_white_01_left.png',
    right: 'vm_white_01_right.png',
    href: storeLink.viuum1,
  },

  gm_beige_02: {
    src: 'gm_beige_02.png',
    left: 'gm_beige_02_left.png',
    right: 'gm_beige_02_right.png',
    href: storeLink.goodmanner2,
  },
  gm_black_02: {
    src: 'gm_black_02.png',
    left: 'gm_black_02_left.png',
    right: 'gm_black_02_right.png',
    href: storeLink.goodmanner2,
  },
  gm_grey_02: {
    src: 'gm_grey_02.png',
    left: 'gm_grey_02_left.png',
    right: 'gm_grey_02_right.png',
    href: storeLink.goodmanner2,
  },
  gm_pink_02: {
    src: 'gm_pink_02.png',
    left: 'gm_pink_02_left.png',
    right: 'gm_pink_02_right.png',
    href: storeLink.goodmanner2,
  },
  gm_white_02: {
    src: 'gm_white_02.png',
    left: 'gm_white_02_left.png',
    right: 'gm_white_02_right.png',
    href: storeLink.goodmanner2,
  },
  hs_white_03: {
    src: 'hs_white_03.png',
    left: 'hs_white_03_left.png',
    right: 'hs_white_03_right.png',
    href: storeLink.hyosung,
  },
  hs_mint_03: {
    src: 'hs_mint_03.png',
    left: 'hs_mint_03_left.png',
    right: 'hs_mint_03_right.png',
    href: storeLink.hyosung,
  },
  hs_navy_03: {
    src: 'hs_navy_03.png',
    left: 'hs_navy_03_left.png',
    right: 'hs_navy_03_right.png',
    href: storeLink.hyosung,
  },
  hs_neonOrange_03: {
    src: 'hs_neonOrange_03.png',
    left: 'hs_neonOrange_03_left.png',
    right: 'hs_neonOrange_03_right.png',
    href: storeLink.hyosung,
  },
  hs_neonPink_03: {
    src: 'hs_neonPink_03.png',
    left: 'hs_neonPink_03_left.png',
    right: 'hs_neonPink_03_right.png',
    href: storeLink.hyosung,
  },
  hs_neonYellow_03: {
    src: 'hs_neonYellow_03.png',
    left: 'hs_neonYellow_03_left.png',
    right: 'hs_neonYellow_03_right.png',
    href: storeLink.hyosung,
  },
  hs_pink_03: {
    src: 'hs_pink_03.png',
    left: 'hs_pink_03_left.png',
    right: 'hs_pink_03_right.png',
    href: storeLink.hyosung,
  },
  hs_red_03: {
    src: 'hs_red_03.png',
    left: 'hs_red_03_left.png',
    right: 'hs_red_03_right.png',
    href: storeLink.hyosung,
  },
  hs_yellow_03: {
    src: 'hs_yellow_03.png',
    left: 'hs_yellow_03_left.png',
    right: 'hs_yellow_03_right.png',
    href: storeLink.hyosung,
  },
  hs_beige_03: {
    src: 'hs_beige_03.png',
    left: 'hs_beige_03_left.png',
    right: 'hs_beige_03_right.png',
    href: storeLink.hyosung,
  },
  hs_black_03: {
    src: 'hs_black_03.png',
    left: 'hs_black_03_left.png',
    right: 'hs_black_03_right.png',
    href: storeLink.hyosung,
  },
  hs_blue_03: {
    src: 'hs_blue_03.png',
    left: 'hs_blue_03_left.png',
    right: 'hs_blue_03_right.png',
    href: storeLink.hyosung,
  },
  hs_charcoal_03: {
    src: 'hs_charcoal_03.png',
    left: 'hs_charcoal_03_left.png',
    right: 'hs_charcoal_03_right.png',
    href: storeLink.hyosung,
  },
  hs_grey_03: {
    src: 'hs_grey_03.png',
    left: 'hs_grey_03_left.png',
    right: 'hs_grey_03_right.png',
    href: storeLink.hyosung,
  },
  hs_lightPink_03: {
    src: 'hs_lightPink_03.png',
    left: 'hs_lightPink_03_left.png',
    right: 'hs_lightPink_03_right.png',
    href: storeLink.hyosung,
  },
  tg_white_04: {
    src: 'tg_white_04.png',
    left: 'tg_white_04_left.png',
    right: 'tg_white_04_right.png',
    href: storeLink.theGreen,
  },
  tg_black_04: {
    src: 'tg_black_04.png',
    left: 'tg_black_04_left.png',
    right: 'tg_black_04_right.png',
    href: storeLink.theGreen,
  },
  tg_burgundy_04: {
    src: 'tg_burgundy_04.png',
    left: 'tg_burgundy_04_left.png',
    right: 'tg_burgundy_04_right.png',
    href: storeLink.theGreen,
  },
  tg_grey_04: {
    src: 'tg_grey_04.png',
    left: 'tg_grey_04_left.png',
    right: 'tg_grey_04_right.png',
    href: storeLink.theGreen,
  },
  tg_mint_04: {
    src: 'tg_mint_04.png',
    left: 'tg_mint_04_left.png',
    right: 'tg_mint_04_right.png',
    href: storeLink.theGreen,
  },
  tg_navy_04: {
    src: 'tg_navy_04.png',
    left: 'tg_navy_04_left.png',
    right: 'tg_navy_04_right.png',
    href: storeLink.theGreen,
  },
  tg_orange_04: {
    src: 'tg_orange_04.png',
    left: 'tg_orange_04_left.png',
    right: 'tg_orange_04_right.png',
    href: storeLink.theGreen,
  },
  tg_pink_04: {
    src: 'tg_pink_04.png',
    left: 'tg_pink_04_left.png',
    right: 'tg_pink_04_right.png',
    href: storeLink.theGreen,
  },
  tg_purple_04: {
    src: 'tg_purple_04.png',
    left: 'tg_purple_04_left.png',
    right: 'tg_purple_04_right.png',
    href: storeLink.theGreen,
  },
  tg_yellow_04: {
    src: 'tg_yellow_04.png',
    left: 'tg_yellow_04_left.png',
    right: 'tg_yellow_04_right.png',
    href: storeLink.theGreen,
  },
};

export const maskObj: {name : string, list : maskType[]}[] = [
  {
    name : '덴탈 마스크',
    list : [
      maskList.tg_grey_04,
    maskList.tg_black_04,
    maskList.tg_burgundy_04,
    maskList.tg_mint_04,
    maskList.tg_navy_04,
    maskList.tg_orange_04,
    maskList.tg_pink_04,
    maskList.tg_purple_04,
    maskList.tg_white_04,
    maskList.tg_yellow_04,
    ]
  },
  {
    name : "네오프렌 마스크",
    list : [
      maskList.hs_beige_03,
    maskList.hs_black_03,
    maskList.hs_blue_03,
    maskList.hs_charcoal_03,
    maskList.hs_grey_03,
    maskList.hs_lightPink_03,
    maskList.hs_mint_03,
    maskList.hs_navy_03,
    maskList.hs_neonOrange_03,
    maskList.hs_neonPink_03,
    maskList.hs_neonYellow_03,
    maskList.hs_pink_03,
    maskList.hs_red_03,
    maskList.hs_white_03,
    maskList.hs_yellow_03,
    ]
  },
  {
    name : "새부리 마스크",
    list : [
      maskList.bts_black_01,
    maskList.bts_cherry_01,
    maskList.bts_green_01,
    maskList.bts_mint_01,
    maskList.bts_orange_01,
    maskList.bts_pink_01,
    maskList.bts_purple_01,
    maskList.bts_skyblue_01,
    maskList.bts_white_01,
    maskList.bts_yellow_01,
    maskList.cz_beige_01,
    maskList.cz_black_01,
    maskList.cz_grey_01,
    maskList.cz_navy_01,
    maskList.cz_white_01,
    maskList.gm_beige_01,
    maskList.gm_black_01,
    maskList.gm_grey_01,
    maskList.gm_pink_01,
    maskList.gm_white_01,
    maskList.gr_beige_01,
    maskList.gr_berry_01,
    maskList.gr_celesteblue_01,
    maskList.gr_coraltint_01,
    maskList.gr_oceanblue_01,
    maskList.gr_peachcushion_01,
    maskList.gr_rosewine_01,
    maskList.vm_ashgrey_01,
    maskList.vm_black_01,
    maskList.vm_gingerbrown_01,
    maskList.vm_grey_01,
    maskList.vm_ivory_01,
    maskList.vm_lightsilver_01,
    maskList.vm_lilacpurple_01,
    maskList.vm_pink_01,
    maskList.vm_sandbeige_01,
    maskList.vm_white_01,
    ]
  }
  ,
  {
    name : '3D 마스크',
    list : [
    maskList.gm_grey_02,
    maskList.gm_beige_02,
    maskList.gm_black_02,
    maskList.gm_pink_02,
    maskList.gm_white_02,  
    ]
  }
];

export type colorType =
  | '봄 브라이트'
  | '봄 라이트'
  | '여름 브라이트'
  | '여름 뮤트'
  | '여름 라이트'
  | '가을 스트롱'
  | '가을 뮤트'
  | '가을 딥'
  | '겨울 딥'
  | '겨울 브라이트';
export const personalColorMask: {
  [key in colorType]: { explain: string; maskList: maskType[] };
} = {
  '봄 브라이트': {
    explain: '봄 브라이트톤은 고명도 고채도의 쨍하고 밝은 색감이 어울려요!',
    maskList: [
      maskList.bts_mint_01,
      maskList.bts_skyblue_01,
      maskList.bts_yellow_01,
      maskList.bts_orange_01,
      maskList.bts_green_01,
      maskList.bts_white_01,
      maskList.gm_white_02,
      maskList.tg_white_04,
      maskList.tg_pink_04,
      maskList.tg_purple_04,
    ],
  },
  '봄 라이트': {
    explain:
      '봄 라이트톤은 저채도의 은은한 파스텔톤 색감과 부드러움이 어울려요!',
    maskList: [
      maskList.cz_beige_01,
      maskList.cz_white_01,
      maskList.gm_beige_01,
      maskList.gm_pink_01,
      maskList.gm_white_01,
      maskList.gr_beige_01,
      maskList.gr_berry_01,
      maskList.gr_celesteblue_01,
      maskList.gr_peachcushion_01,
      maskList.gr_rosewine_01,
      maskList.hs_lightPink_03,
      maskList.hs_white_03,
      maskList.vm_ivory_01,
      maskList.vm_lilacpurple_01,
      maskList.vm_pink_01,
      maskList.vm_lightsilver_01,
      maskList.vm_white_01,
      maskList.vm_sandbeige_01,
    ],
  },
  '여름 브라이트': {
    explain:
      '여름 브라이트는 고명도 고채도의 쨍한 색감으로 블루베이스의 시원한 색이 어울려요!',
    maskList: [
      maskList.bts_mint_01,
      maskList.bts_purple_01,
      maskList.bts_skyblue_01,
      maskList.bts_green_01,
      maskList.gr_berry_01,
      maskList.gr_celesteblue_01,
      maskList.gr_coraltint_01,
      maskList.gr_rosewine_01,
      maskList.hs_lightPink_03,
      maskList.hs_pink_03,
      maskList.tg_orange_04,
      maskList.tg_purple_04,
      maskList.vm_lilacpurple_01,
    ],
  },
  '여름 라이트': {
    explain: '여름 라이트는 고명도 저채도의 쿨하고 밝은 톤이 어울려요!',
    maskList: [
      maskList.cz_white_01,
      maskList.gm_beige_01,
      maskList.gm_pink_01,
      maskList.gm_white_01,
      maskList.gr_berry_01,
      maskList.gr_celesteblue_01,
      maskList.gr_peachcushion_01,
      maskList.gr_rosewine_01,
      maskList.hs_lightPink_03,
      maskList.hs_white_03,
      maskList.vm_lilacpurple_01,
      maskList.vm_pink_01,
      maskList.vm_lightsilver_01,
      maskList.vm_white_01,
    ],
  },
  '여름 뮤트': {
    explain: '여름 뮤트는 너무 밝은 색보단 톤 다운된 쿨한 색감이 어울려요!',
    maskList: [
      maskList.cz_grey_01,
      maskList.cz_navy_01,
      maskList.gm_grey_01,
      maskList.gm_grey_02,
      maskList.gm_pink_02,
      maskList.gr_beige_01,
      maskList.gr_berry_01,
      maskList.gr_oceanblue_01,
      maskList.hs_charcoal_03,
      maskList.hs_grey_03,
      maskList.hs_lightPink_03,
      maskList.hs_mint_03,
      maskList.hs_navy_03,
      maskList.tg_grey_04,
      maskList.tg_navy_04,
      maskList.tg_purple_04,
      maskList.vm_ashgrey_01,
      maskList.vm_gingerbrown_01,
      maskList.vm_grey_01,
    ],
  },
  '가을 뮤트': {
    explain: '가을 뮤트는 중간 계열 색감으로 다운되고 따뜻한 색이 어울려요!',
    maskList: [
      maskList.cz_grey_01,
      maskList.cz_beige_01,
      maskList.gm_grey_01,
      maskList.gm_grey_02,
      maskList.gm_grey_02,
      maskList.gm_pink_02,
      maskList.gr_beige_01,
      maskList.gr_berry_01,
      maskList.gr_peachcushion_01,
      maskList.gr_rosewine_01,
      maskList.hs_charcoal_03,
      maskList.hs_grey_03,
      maskList.hs_beige_03,
      maskList.hs_lightPink_03,
      maskList.hs_mint_03,
      maskList.tg_grey_04,
      maskList.tg_purple_04,
      maskList.vm_ashgrey_01,
      maskList.vm_gingerbrown_01,
      maskList.vm_grey_01,
      maskList.vm_lightsilver_01,
    ],
  },
  '가을 스트롱': {
    explain:
      '가을 스트롱은 적당한 밝기의 채도가 높은 비비드한 색감이 어울려요!',
    maskList: [
      maskList.bts_cherry_01,
      maskList.bts_mint_01,
      maskList.bts_orange_01,
      maskList.bts_purple_01,
      maskList.gr_oceanblue_01,
      maskList.hs_blue_03,
      maskList.hs_navy_03,
      maskList.hs_neonOrange_03,
      maskList.hs_neonYellow_03,
      maskList.hs_pink_03,
      maskList.tg_burgundy_04,
      maskList.tg_navy_04,
    ],
  },
  '가을 딥': {
    explain:
      '가을 딥은 채도 높은 원색에 검은색이 섞인 듯 깊고 그윽한 색이 어울려요!',
    maskList: [
      maskList.bts_black_01,
      maskList.bts_orange_01,
      maskList.cz_black_01,
      maskList.cz_navy_01,
      maskList.gm_black_01,
      maskList.gm_black_02,
      maskList.gr_oceanblue_01,
      maskList.hs_black_03,
      maskList.hs_blue_03,
      maskList.hs_charcoal_03,
      maskList.hs_navy_03,
      maskList.tg_black_04,
      maskList.tg_burgundy_04,
      maskList.tg_navy_04,
      maskList.vm_black_01,
      maskList.vm_gingerbrown_01,
    ],
  },
  '겨울 브라이트': {
    explain: '겨울 브라이트는 고채도의 비비드한 네온 컬러가 잘어울려요!',
    maskList: [
      maskList.bts_cherry_01,
      maskList.bts_mint_01,
      maskList.bts_orange_01,
      maskList.bts_purple_01,
      maskList.gr_berry_01,
      maskList.gr_oceanblue_01,
      maskList.gr_coraltint_01,
      maskList.hs_blue_03,
      maskList.hs_neonPink_03,
      maskList.hs_neonOrange_03,
      maskList.hs_neonYellow_03,
      maskList.hs_pink_03,
      maskList.tg_purple_04,
    ],
  },
  '겨울 딥': {
    explain: '겨울 딥은 채도가 낮고 무겁지만 쿨한 색감이 어울려요!',
    maskList: [
      maskList.bts_black_01,
      maskList.bts_cherry_01,
      maskList.cz_black_01,
      maskList.cz_navy_01,
      maskList.gm_black_01,
      maskList.gm_black_02,
      maskList.gr_oceanblue_01,
      maskList.hs_black_03,
      maskList.hs_blue_03,
      maskList.hs_charcoal_03,
      maskList.hs_navy_03,
      maskList.tg_black_04,
      maskList.tg_burgundy_04,
      maskList.tg_navy_04,
      maskList.vm_black_01,
      maskList.vm_gingerbrown_01,
    ],
  },
};
